name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
  workflow_dispatch:
    # allow this workflow to be triggered manually

jobs:
  builder:
    name: 'Build and test on ${{ matrix.arch }}-${{ matrix.os }}/${{ matrix.dc }}'
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ contains(matrix.dc, 'beta') }}
    env:
      ARCH: ${{ matrix.arch }}
    strategy:
      fail-fast: false
      matrix:
        dc: [ldc-latest, ldc-beta, dmd-latest, dmd-beta]
        os: [ubuntu-latest, windows-latest]
        arch: [x86, x86_64]
        include:
          - dc: ldc-latest
            os: macos-latest
            arch: x86_64
          - dc: dmd-latest
            os: macos-latest
            arch: x86_64
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
      - uses: dlang-community/setup-dlang@763d869b4d67e50c3ccd142108c8bca2da9df166
        with:
          compiler: ${{ matrix.dc }}
      - name: Install multi-lib for 32-bit systems
        if: matrix.arch == 'x86' && matrix.os == 'ubuntu-latest'
        run: sudo apt-get install gcc-multilib
      - id: build
        name: Test library
        run: |
          dub test --arch=$ARCH
        shell: bash